name: "Cloudflare Clear Cache"
description: "Clears a zone's cache via the Cloudflare API"
author: Cyb3r-Jake
runs:
  using: docker
  image: "docker://cyb3rjak3/docker-curl-ssh"
  entrypoint: entrypoint.sh
branding:
  icon: 'zap'  
  color: 'purple'

inputs:
  zone:
    description: "The Zone ID of your domain, which can be found in the right sidebar of your domain's overview page on the Cloudflare dashboard."
    required: true
  email:
    description: "The email address you registered your Cloudflare account with."
    required: false
  global_key:
    description: "Your Global Cloudflare API key. Highly not recommended to use"
    required: false
  api_token:
    description: "A Cloudflare API Token"
    required: false
  urls:
    required: false
    description: "The specific URLs to purge (a STRING in JSON format '["https://blog.jwhite.network", "https://blog.jwhite.network/about.png"]')"